version: '3.9'

services:
  paradise-mysql:
    image: mysql
    container_name: paradise_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=109339Lam@
      - MYSQL_DATABASE=paradise
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - paradise_network

  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - go01-airbnb

  api:
    depends_on:
      - paradise-mysql
      # - redis
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paradise-app-api
    ports:
      - "8081:8081"
    networks:
      - paradise_network
volumes:
  database_mysql:

networks:
  paradise_network:
    driver: bridge