app:
  Version: 1.0.0
  Port: 8081
  Mode: development
  Secret: 109339Lam
  MigrationURL:  file://migrations

mysql:
  #Host: paradise-mysql
  # Host: localhost
  # ContainerName: paradise_mysql
  # Port: 3306
  # User: root
  # Password: 109339Lam@
  # DBName: paradise
  Host: viaduct.proxy.rlwy.net
  Port: 13281
  User: root
  Password: ahf3hhDgEdBD1ea4cA-1G4AeDAd1hHE3
  DBName: railway

aws:
  Region: ap-southeast-1
  APIKey: AKIAXFND7G2RDKLZP6WM
  SecretKey: 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
  S3Domain: d24vk7oviyillz.cloudfront.net
  S3Bucket: lamhieogo

redis:
  #Host: redis
  Host: localhost
  Port: 6379
  Password: ""
  DB: 0

google:
  ClientID: 701762046284-1o7u891fgp06kvi0f7344dikclpmjdmq.apps.googleusercontent.com
  ClientSecret: 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
  RedirectURL: http://localhost:3000/

email:
  EmailSenderName: LamNguyen
  EmailSenderAddress: lamfan011@gmail.com
  EmailSenderPassword: earzqfmxxcxorlxz
