app:
  Version: 1.0.0
  Port: 8081
  Mode: development
  Secret: 109339Lam
  MigrationURL:  file://migrations

mysql:
  #Host: paradise-mysql
  # Host: localhost
  # ContainerName: paradise_mysql
  # Port: 3306
  # User: root
  # Password: 109339Lam@
  # DBName: paradise
  Host: viaduct.proxy.rlwy.net
  Port: 13281
  User: root
  Password: ahf3hhDgEdBD1ea4cA-1G4AeDAd1hHE3
  DBName: railway

aws:
  Region: ap-southeast-1
  APIKey: AKIAXFND7G2RAL4ME35U
  SecretKey: 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
  S3Domain: d1dblnjcawoqkg.cloudfront.net
  S3Bucket: paradisebooking
  S3FolderImages: images
redis:
  #Host: redis
  Host: redis-17757.c295.ap-southeast-1-1.ec2.cloud.redislabs.com
  Port: 17757
  Password: ZEW6dhRArdcKBxmzNLh6dRVQnAwV04bk
  DB: 0

google:
  ClientID: 701762046284-1o7u891fgp06kvi0f7344dikclpmjdmq.apps.googleusercontent.com
  ClientSecret: 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
  RedirectURL: http://localhost:3000/

email:
  EmailSenderName: LamNguyen
  EmailSenderAddress: lamfan011@gmail.com
  EmailSenderPassword: earzqfmxxcxorlxz
